epc <- read.table("household_power_consumption.txt" , sep= ";" , header = T , na.strings = "?" , as.is = 1:2)
epc$Date <- as.Date(epc$Date , "%d/%m/%Y")
set <- subset(epc,Date == "2007-02-01" | Date == "2007-02-02")
png('plot3.png' , width = 480 , height = 480)
plot(set$Sub_metering_1 , type = "l" , xlab = "" , ylab = "Energy sub metering", xaxt ='n')
lines(set$Sub_metering_2 , col = "red")
lines(set$Sub_metering_3 , col = "blue")
ticks <- c(0,nrow(set)/2 , nrow(set))
axis(1,at = ticks,labels = c("Thu","Fri","Sat"))
legend("topright" , colnames(set)[7:9] , col = c("black","red","blue") , lty = 1)
dev.off()