epc <- read.table("household_power_consumption.txt" , sep= ";" , header = T , na.strings = "?" , as.is = 1:2)
epc$Date <- as.Date(epc$Date , "%d/%m/%Y")
set <- subset(epc,Date == "2007-02-01" | Date == "2007-02-02")
png('plot1.png' , width = 480 , height = 480)
hist(set$Global_active_power , xlab = "Global Active Power (Killowatts)" , main = "Global Active Power", xlim = c(0,6) , col = "red")
dev.off()
